version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    hostname: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8180:8080
  app:
    image: munkalap:latest
    build:
      context: .
    container_name: munkalap
    hostname: munkalap
    environment:
      - keycloak.auth-server-url=http://keycloak:8080/auth
    ports:
      - 8080:8080