version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    hostname: keycloak
    ports:
      - 8180:8080
    entrypoint: "/keycloak/entrypoint.sh"
    volumes:
      - ./keycloak:/keycloak
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: worksheet
      MYSQL_USER: worksheet
      MYSQL_PASSWORD: worksheet
  app:
    image: munkalap:latest
    build:
      context: .
    container_name: munkalap
    hostname: munkalap
    environment:
      - keycloak.auth-server-url=http://keycloak:8080/auth
    ports:
      - 8080:8080
