server:
  port: 8081

hu:
  flowacademy:
    worksheet:
      paging:
        defaultLimit: 10

spring:
  http:
    encoding: charset=UTF-8
    enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/worksheet
    username: worksheet
    password: worksheet
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

keycloakBackendClient:
  realm: master
  client-id: admin-cli
  adminusername: gyanyim
  adminpassword: snxTZr9$5GGnS7w
  user-role: worksheetuser

keycloak:
  realm: worksheet
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: worksheetclient
  credentials.secret: be835fad-eba0-4797-ad88-b802b676d2f3
  use-resource-role-mappings: true
  bearer-only: true
