server:
  port: 8081

hu:
  flowacademy:
    worksheet:
      paging:
        defaultLimit: 10

spring:
  datasource:
    url: jdbc:mysql://localhost:8081/db_example
    username: worksheet
    password: worksheet
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

keycloakBackendClient:
  realm: master
  client-id: admin-cli
  adminusername: gyanyim
  adminpassword: snxTZr9$5GGnS7w
  user-role: worksheetuser

keycloak:
  realm: worksheet
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: worksheetclient
  credentials.secret: be835fad-eba0-4797-ad88-b802b676d2f3
  use-resource-role-mappings: true
  bearer-only: true
